project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Coronary Artery Bypass Graft (CABG) Complications"
  author:
    - Jordan Jomsky (jj3379)
    - Jacob Meyer (jtm2217)
  repo-url: https://github.com/20jmeyer/CABG-Complications
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


