# Conclusion

## Main Takeaways
From our analysis, we can draw several conclusions about the relationships between demographic and medical data, CABG complication data, and post-CABG hospital readmission data. 

First, `Other` Insurance type was one of the greatest predictors of readmission. We saw nearly no one with `Other` Insurance be readmitted to the hospital no matter what their complication was. Even though we do not know what exact insurance this strata contains, we can speculate that it is group plans offered through work. In this case, it may be better overall insurance, increasing the quality of care they receive initially for their complications and thereby preventing readmission.

Second, `Black` and `Hispanic` for the `Race` category and `Female` for the `Gender` category were almost always more likely to be readmitted to the hospital, especially for `Post-Operative Atrial Fibrillation`, `Post-Operative Dialysis`, and `Post-Operative Renal Failure`. This indicates a possible gap in quality care for these underrepresented communities, further backed up by the lack of actual patients for all these groups. 

We also saw some other tangential conclusions. We consistently saw an inverse relationship between `Post-Operative Atrial Fibrillation` and `Prolonged Ventilation` for nearly every strata and complication comparison. This may suggest that risk factors for each complication are opposite from each other. Also, `Age` is not as strong of a predictor as we previously thought would be due to the increased risk factors of heart disease with increased age. 

## Limitations
One major limitation of this analysis is the fact that the data was de-identified healthcare data. Chiefly, this data lacked the eventual health outcomes of the patients. While this is understandable safeguard for patient privacy, it made our eventual conclusions about the data weaker because we do not know if the readmissions or lack thereof were necessarily adverse outcomes without the information. Instead, our conclusions are related to readmission to the hospital which could lead to positive or negative outcome for overall health. Further, in analyzing demographic data, the lack of data showing the relationship between demographics prevents exploration into the intersectional nature of these factors and their relationship to surgical complications and hospital readmission rates. The ambiguity of the data overall including the lack of clarity on other categories in the `Insurance Type` and `Surgical Procedure` categories.

## Future Directions
A possible future direction would be to look into the several significant relationships our analysis uncovered. Data would need to be collected with specific attention paid to marginalized groups. Moreover, the relationship between `Insurance Type` and `Readmission` is puzzling at best, especially with the ambiguity of the data previously discussed. A study into this strong dependence would be illuminating to the cause of this relationship.

## Lessons Learned
Mosaics plots are much harder to compare across different sample sizes. When faceting on `Complication` to create mosaic plots for `Readmission` and each category's strata, having the plots being the same size next to each other was a bit misleading about the differences in the length and width worked in relation to each other. The $\chi^2$ tests helped handle this issue as it showed empirically what relationships were significant and which were not. In the future, making some more custom visualization like a proportional mosaic combined into one plot to show all relationships at once with overall frequency considered.
