# Data
```{r}
library(ggplot2)
library(tidyverse)
library(dplyr)
library(ggalluvial)
library(RColorBrewer)

cabg = read.csv("cab.csv")
cabg
```

```{r}
cabg_counts = cabg %>% subset(category=="All") %>% arrange(Year, complication) %>% select(-c(category, Strata))
cabg_counts
```

```{r}
alluvial_counts = cabg_counts %>% group_by(Year, complication) %>% summarise(Freq=sum(Count))
readmission_counts = cabg_counts %>% group_by(Year, readmission) %>% summarise(Freq=sum(Count))
```



```{r}
ggplot(alluvial_counts, aes(x=Year, y=Freq, alluvium=complication, fill=complication, label=complication)) + 
  scale_fill_brewer(type = "qual", palette = "Set2") +
  geom_flow(stat = "alluvium", width=0) +
  theme_minimal()
```


```{r}
ggplot(readmission_counts, aes(x=Year, y=Freq, alluvium=readmission, fill=readmission, label=readmission)) + 
  scale_fill_brewer(type = "qual", palette = "Set2") +
  geom_flow(stat = "alluvium", width=0) +
  theme_minimal()
```

```{r}
raw_data = cabg %>% subset(category!="All") %>% select(-Yes)
raw_data %>%
  pivot_wider(
    id_cols = c(Year, complication, Strata, readmission),
    names_from = category,
    values_from = Count,
    values_fill = list(Count = 0)
  )
```

```{r}
heatmap_data <- cabg %>% subset(category!="All") %>%
  group_by(Year, complication, category, Strata) %>%
  summarise(Count = sum(Count)) %>%
  ungroup() 

ggplot(data = heatmap_data, aes(x = Strata, y = Strata)) +
  geom_tile() +
  labs(title = "Overlap of Strata in Data Heatmap", x = "Strata", y = "Strata") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r fig.height=10, fig.width=15}
ggplot(raw_data, aes(x = Strata, y = Count, fill = Strata)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~ category, scales = "free") +
  labs(title = "Counts across Strata for Categories",
       x = "Strata", y = "Count") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(fill = guide_legend(title = "Strata"))
```


```{r}

```


## Description

## Missing value analysis
