# Results
```{r}
library(ggplot2)
library(tidyverse)
library(dplyr)
library(ggalluvial)
library(RColorBrewer)
options(dplyr.summarise.inform = FALSE)

cab = read.csv("cab.csv")
cab = cab %>% mutate(Strata = factor(Strata)) %>% mutate(Strata = fct_recode(Strata, "Over 65" = "66 to Max", "Under 40" = "0 to 40"))
```


```{r}
cab_counts = cab %>% arrange(Year, complication)
head(cab_counts)
```



# Question 1: Does our data change over time in terms of frequency of complications, readmissions, and demographics/medical information?
```{r}
complication_counts = cab_counts %>% group_by(Year, complication) %>% summarise(Freq=sum(Count))
readmission_counts = cab_counts %>% group_by(Year, readmission) %>% summarise(Freq=sum(Count))
strata_counts = cab_counts %>% group_by(Year, category, Strata) %>% summarise(Freq=sum(Count)) %>% subset(category != "All")
strata_counts
```

```{r}
ggplot(complication_counts, aes(x=Year, y=Freq, fill=complication)) +
  geom_bar(stat='identity', position='dodge') +
  scale_fill_brewer(palette="Dark2") +
  labs(title="Counts of Complications over the Years", y="Count")
ggplot(complication_counts, aes(x=Year, y=log10(Freq), fill=complication)) +
  geom_bar(stat='identity', position='dodge') +
  scale_fill_brewer(palette="Dark2") +
  labs(title="Log Counts of Complications over the Years", y="Log Count")
```

```{r}
ggplot(readmission_counts, aes(x=Year, y=Freq, fill=readmission)) +
  geom_bar(stat='identity', position='dodge') +
  scale_fill_brewer(palette="Dark2") +
  labs(title="Counts of Readmissions over the Years", y="Count")
```

```{r fig.height=6, fig.weight=6}
for (c in unique(strata_counts$category)) {
  print(ggplot(strata_counts %>% subset(category == c), aes(x=Year, y=Freq, fill=Strata)) +
    geom_bar(stat='identity', position='dodge') +
    scale_fill_brewer(c, palette="Dark2") +
    labs(title=paste(paste("Counts of", c), "over the Years"), y="Count") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)))
}
```

# Question 2: What are the most common complications associated with CABG?
```{r}
complication_counts %>% group_by(complication) %>% summarize(Freq=sum(Freq))
```




